spring:
  datasource:
    username: root
    password: hfb.mysql
    url: jdbc:mysql://111.229.16.18:3306/student?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false